name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  dependabot-pr-auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'

    steps:
      - name: Suite Status Checks
        id: suite-checks
        uses: poseidon/wait-for-status-checks@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: dependabot-email-notification

      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2

      - name: Auto-merge Dependabot PR
        run: |
          gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}